In [4]:
import numpy as np  #导入Numpy的包

In [2]:
arr1 = np.array([[1,2,3],
          [4,5,6],
          [7,8,9]]
        )#创建一个3*3的矩阵
print(arr1) #输出矩阵

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
arr2 = np.arange(1,10)  #用序列生成一个数组
print(arr2)
print(arr2.shape)  #数组的形状，注意一维数组是（n,）
print(arr2.shape)

[1 2 3 4 5 6 7 8 9]
(9,)
(9,)


In [8]:
arr3 = arr2.reshape(3,3).T   #重新定义维度，然后转置
print(arr3)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [13]:
print(arr3.shape)  #形状
print(arr3.ndim)   #维度
print(arr3.itemsize)  #每个元素的字节大小
print(arr3.size)   #数组中有多少个元素
print(arr3.dtype)  #数组中元素的类型

(3, 3)
2
4
9
int32


In [15]:
arr5 = np.zeros((3,3))  #元素均为0的数组
arr6 = np.empty((3,3))  #元素接近0的数组
print(arr5)
print(arr6)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 6.28451502e-321]
 [9.34605036e-307 8.34451503e-308 2.46155397e-312]]


In [66]:
arr6 = np.random.rand(5,10)  #随机数
print(arr6)

arr7 = np.random.randn(5,10)  #随机数，且符合正态分布
print(arr7)

arr8 = np.random.normal(1,2,10)  #正态分布的值
# 三个参数分别如下：
# loc：float
#     此概率分布的均值（对应着整个分布的中心centre）
# scale：float
#     此概率分布的标准差（对应于分布的宽度，scale越大越矮胖，scale越小，越瘦高）
# size：int or tuple of ints
#     输出的shape，默认为None，只输出一个值
print(arr8)

[[0.25314186 0.8117349  0.77484645 0.65135541 0.50042803 0.21412059
  0.56640501 0.81582361 0.3225263  0.33999898]
 [0.95342955 0.84173344 0.30296648 0.6250254  0.37458929 0.03111383
  0.00862008 0.73957544 0.65424288 0.32332768]
 [0.05137438 0.52305162 0.38485258 0.8115977  0.11228627 0.24273322
  0.32874904 0.83433858 0.55733501 0.85985372]
 [0.16553904 0.09418449 0.24241416 0.8318896  0.69458439 0.4990254
  0.93170178 0.85622624 0.90195424 0.36133039]
 [0.14510534 0.99841947 0.10269642 0.95711647 0.9090924  0.21207529
  0.28822037 0.66891734 0.78102118 0.06151659]]
[[-1.01966125 -0.40977304  0.57821859 -0.73453107 -0.16981404  0.07795546
  -1.11306799 -1.44998834  0.86116082  0.88450994]
 [-1.79109005 -0.57450445  0.8418166  -0.98780904  0.99217887  0.68759178
   0.28900736 -0.32297942  0.32550914  0.43821943]
 [ 1.15760512  0.34886334  0.57162137 -0.09428946 -0.89223864 -2.21369365
   0.01066882  0.17107512  0.5637913   0.49417322]
 [ 0.22241405 -0.25831922 -1.61649056 -0.27486736 

In [28]:
arr10 = np.arange(1,10)
print(arr10)
arr11 = arr10.reshape((3,3))
print(arr11)

arr12 = arr11.T
print(arr12)
arr13 = arr12  #这是浅拷贝，原件与复印件同时修改
arr13[1,2] = 100
print(arr12)

arr14 = np.copy(arr12)  #这是深度拷贝，原件与复印件之间没有关系了！！！
arr14[1,2] = 500
print(arr12)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[  1   4   7]
 [  2   5 100]
 [  3   6   9]]
[[  1   4   7]
 [  2   5 100]
 [  3   6   9]]


In [33]:
print(arr12)
print(arr12[0,0:1])  #通过下标访问元素

[[  1   4   7]
 [  2   5 100]
 [  3   6   9]]
[1]


In [39]:
print(arr12)
print(arr13)
arr20 = np.vstack((arr12,arr13))  #合并数组
print(arr20)

[[  1   4   7]
 [  2   5 100]
 [  3   6   9]]
[[  1   4   7]
 [  2   5 100]
 [  3   6   9]]
[[  1   4   7]
 [  2   5 100]
 [  3   6   9]
 [  1   4   7]
 [  2   5 100]
 [  3   6   9]]


In [47]:
print(arr20)
print(np.vsplit(arr20,2))  #分割数组

[[  1   4   7]
 [  2   5 100]
 [  3   6   9]
 [  1   4   7]
 [  2   5 100]
 [  3   6   9]]
[array([[  1,   4,   7],
       [  2,   5, 100],
       [  3,   6,   9]]), array([[  1,   4,   7],
       [  2,   5, 100],
       [  3,   6,   9]])]


In [52]:
print(arr1)
print(arr3)
#print(arr1 * arr3)
print(np.dot(arr1,arr3))  #矩阵的点乘

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[ 14  32  50]
 [ 32  77 122]
 [ 50 122 194]]


In [54]:
print(arr1,arr3)
print(arr1*arr3)  #按位相乘

[[1 2 3]
 [4 5 6]
 [7 8 9]] [[1 4 7]
 [2 5 8]
 [3 6 9]]
[[ 1  8 21]
 [ 8 25 48]
 [21 48 81]]


In [58]:
print(arr3)
arr100 = arr3.ravel()  #展开为一维数组
arr101 = np.sort(arr100)  #对展开后的数组进行排序
print(arr101)

[[1 4 7]
 [2 5 8]
 [3 6 9]]
[1 2 3 4 5 6 7 8 9]


In [63]:
print(arr3)
print(arr3.sum())  #求所有元素的和
print(arr3.cumsum())  #求元素的累和
print(np.argmax(arr3))  #求最大值的下标
print(np.median(arr3))  #求中位数的下标

[[1 4 7]
 [2 5 8]
 [3 6 9]]
45
[ 1  5 12 14 19 27 30 36 45]
8
5.0
